name: Deploy to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "web-application/**"
      - ".github/workflows/deploy.yaml"
      - "docker-compose.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/atlas-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./web-application
          file: ./web-application/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/atlas-frontend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            cd /root/application
            git pull origin main
            docker-compose pull
            docker-compose up -d
