name: Versioning

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # чтобы получить все теги

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_version
        run: |
          latest_tag="${{ steps.get_tag.outputs.latest_tag }}"
          version="${latest_tag#v}"
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Push new tag
        env:
          NEW_TAG: ${{ steps.bump_version.outputs.new_tag }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
          echo "Tag $NEW_TAG already exists"
          exit 1
          fi
          git tag $NEW_TAG
          # Пробуем оба варианта (один из них должен сработать)
          git push https://$PAT_TOKEN@github.com/hse-atlas/application.git $NEW_TAG || \
          git push https://x-access-token:$PAT_TOKEN@github.com/hse-atlas/application.git $NEW_TAG
